### ISSUE TITLE
Weights not loaded with Google Chrome 

### ISSUE THREAD

**Issue by djebm2** [transcranial/keras-js#13]
`Loading ... 0% ` That's what I've got.

Works perfectly with Firefox though.

System: Ubuntu 16.04 LTS with NVIDIA Titan X Pascal.

**Comment by transcranial** [comment]
@djebm2 do you see any errors when you open up chrome devtools?

**Comment by djebm2** [comment]
That's the error.

`XMLHttpRequest cannot load file:///home/djeb/keras-js/demos/data/imdb_bidirectional_lstm/imdb_bidirectional_lstm.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

**Comment by hpssjellis** [comment]
I was using an old version of Chrome (Ver41.) and keras-js was partially working. Updated chrome (Ver54.) and it is now fully working.

**Comment by djebm2** [comment]
Error still persisting with version 54.

**Comment by leo6104** [comment]
As written in README.md, data is loaded over XHR (same-domain or CORS required).
So, you should build web server and serve html over http. (opening local html file is not proper method.)
