### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by AlexanderKozhevin** [transcranial/keras-js#15]
webgl.js:56Uncaught TypeError: Cannot read property 'getShaderPrecisionFormat' of null
keras.js:4 Uncaught TypeError: Cannot read property 'getParameter' of null
bundle.js:15n @ bundle.js:1(anonymous function) @ bundle.js:1(anonymous function) @ bundle.js:1

![screen shot 2016-10-16 at 12 17 16](https://cloud.githubusercontent.com/assets/4464561/19416538/e82da5c8-939b-11e6-85c9-3c6c7a7a8e28.png)

**Comment by leo6104** [comment]
https://developer.mozilla.org/en/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL
"Unable to initialize WebGL. Your browser may not support it."

In 'src/constants.js' file, 
`const gl = canvas.getContext('webgl') || canvas.getContext('experimental-webgl')
export const MAX_TEXTURE_SIZE = gl.getParameter(gl.MAX_TEXTURE_SIZE)
`

it cause that error.

**Comment by kevinmartinmauro** [comment]
Is there a way to bypass this? I thought WebGL support would be optional based on the readme. I just want CPU usage.

**Comment by stekaiser** [comment]
Yes, change your `src/constants.js` to something like this: https://github.com/stekaiser/keras-js/blob/webgl-disabled/src/constants.js.

**Comment by kevinmartinmauro** [comment]
I love you. It's 4am here
