### ISSUE TITLE
Tests - Merge dot, cos operation Assertion Error

### ISSUE THREAD

**Issue by leo6104** [transcranial/keras-js#18]
**dot**
>**[core.Merge.9] should produce expected values in dot mode (2D x 2D, dotAxes=1) ‣
AssertionError: expected [ 3, 3 ] to deeply equal [ 2, 2 ]**
**[core.Merge.10] should produce expected values in dot mode (2D x 2D, dotAxes=2) ‣
AssertionError: expected [ 2, 2 ] to deeply equal [ 3, 3 ]**

**cos**
>**[core.Merge.11] should produce expected values in cos mode (2D x 2D, dotAxes=1) ‣
AssertionError: expected [ 1, 3, 3 ] to deeply equal [ 1, 2, 2 ]**
**[core.Merge.12] should produce expected values in cos mode (2D x 2D, dotAxes=2) ‣
AssertionError: expected [ 1, 2, 2 ] to deeply equal [ 1, 3, 3 ]**

**Comment by transcranial** [comment]
Thanks for catching these, will have a look.
