### ISSUE TITLE
Runtime Bug

### ISSUE THREAD

**Issue by FuriouslyCurious** [transcranial/keras-js#2]
Excellent project Leon!  While running the demos using existing images, computational flow seems to stop 2-3 layers before end.  I am running Firefox 49 on Mac OSX. 

If you cannot replicate this, I can send you debug info from the console. 

Great job again!

**Comment by transcranial** [comment]
Thanks for the report. Firefox 49 in Ubuntu 14.04 and 16.04 work fine, but I just checked with Firefox 49 in OS X and am running into issues as well. Strange, will investigate.

**Comment by transcranial** [comment]
Firefox on certain platforms (macOS in particular, possibly others) still has texture size limits hard-coded. Even on modern GPUs, this limit may be too low. This is a [known issue](https://bugzilla.mozilla.org/show_bug.cgi?id=986871). While Keras.js will gracefully downgrade to use the CPU in this case, computational performance will be degraded. One way to get around this is to go to `about:config` and change `gfx.work-around-driver-bugs` to `false`, and restart the browser. This should increase the max texture size back to normal.
