### ISSUE TITLE
Can I use my own model?

### ISSUE THREAD

**Issue by prithi** [transcranial/keras-js#20]
Can I use my own model in keras.js? If yes then how?

**Comment by madebyollin** [comment]
See [Usage](https://github.com/transcranial/keras-js#usage) in the ReadMe.  You'll want to use keras's `json` export and the provided `encoder.py` to generate the files, then you can link to them in keras.js.

**Comment by sanjuprk** [comment]
**then you can link to them in keras.js**

How to do this part ..?
