### ISSUE TITLE
TypeError: this.weights.W.weblasTensor is undefined

### ISSUE THREAD

**Issue by hzitoun** [transcranial/keras-js#21]
Demos don't work on firefox 49.0 running on linux mint.
Here is the stack trace
![issue](https://cloud.githubusercontent.com/assets/5884465/19828441/f0a7ff1c-9dc5-11e6-9aad-cfcba65d96f6.png)

**Comment by transcranial** [comment]
Hmm not sure how to reproduce this specific error. There are still various outstanding issues with firefox, though.

**Comment by transcranial** [comment]
This bug should be fixed. However, firefox on certain platforms still has texture size limits hard-coded (https://bugzilla.mozilla.org/show_bug.cgi?id=986871), which will degrade computational performance. `about:config` and changing `gfx.work-around-driver-bugs` to `false` may fix this.

**Comment by hzitoun** [comment]
Actually this  commit https://github.com/transcranial/keras-js/commit/598c4fd50abbe7cfe998ffbfd74226ce7a2f51ef fixes the problem :+1:  No need to  change Firefox's config.
