### ISSUE TITLE
conv2d_tranpose in keras js?

### ISSUE THREAD

**Issue by lengstrom** [transcranial/keras-js#24]
Is there any known workaround for using `conv2d_tranpose` in keras.js? (which doesn't look like it is supported?)

**Comment by transcranial** [comment]
`conv2d_transpose` is abstracted by the `Deconvolution2D` layer. The variational autoencoder example uses this:

https://github.com/transcranial/keras-js/blob/master/demos/notebooks/mnist_vae.ipynb
https://transcranial.github.io/keras-js/#/mnist-vae

At this point, there's no way to use tensorflow ops directly. Everything works through keras layers only.
