### ISSUE TITLE
Multiple named inputs need to be listed in order

### ISSUE THREAD

**Issue by zo7** [transcranial/keras-js#31]
I have a model with two inputs named `input_a` and `input_b`, defined in that order.

Trying to make a prediction with a keras.js model, this works:

    model.predict({'input_a': data_a, 'input_b': data_b})
        .then(outputData => {
            // ...
        })

However, if you order them backwards in the object being passed to `model.predict()`, it throws an error:

    model.predict({'input_b': data_b, 'input_a': data_a})
        .then(outputData => {
            // ...
        })

> Error: predict() must take an object where the keys are the named inputs of the model: input_a,input_b.

Yikes! Small problem, but it stumped me for about an hour to figure out why it wasn't working, and the error message is misleading in this case

Great work, btw!

**Comment by transcranial** [comment]
@zo7 sorry about that! you're right, ordering of the inputs shouldn't matter -- should be fixed now.

**Comment by zo7** [comment]
@transcranial Awesome! :D
