### ISSUE TITLE
Merge  layer , mode 'dot' implementation

### ISSUE THREAD

**Issue by aferdoash** [transcranial/keras-js#34]
I think the implementation of 'dot' mode for Merge layer ignores the fact that the dot axis can be a tuple too instead of an integer. When a tuple dotAxes is sent as part of attr to Merge layer for dot mode in Merge.js 
`    this.dotAxes = dotAxes <= 0
      ? dotAxes
      : dotAxes - 1`   sets  `this.dotAxes` to NaN

**Comment by transcranial** [comment]
Thanks for catching this. Should be fixed now.
