### ISSUE TITLE
[Conv1D] TypeError: this.weights.b is undefined

### ISSUE THREAD

**Issue by stekaiser** [transcranial/keras-js#36]
I'm getting this error when running a `Convolution1D` model. The error is probably due to `this.bias` being undefined [here](https://github.com/transcranial/keras-js/blob/master/src/layers/convolutional/Convolution1D.js#L34).

Setting `this.bias = true` before that line resolves the error. Is there a smarter way than doing that? E.g. looking up if the bias contained in the weights metadata?

Possibly related to #21?

**Comment by transcranial** [comment]
That was sloppy of me; should be fixed. Thanks for reporting!
