### ISSUE TITLE
Fira sans is broken in Chrome and Firefox on Linux

### ISSUE THREAD

**Issue by rkfg** [transcranial/keras-js#39]
On Debian testing at least but probably on other distros as well. Could be also broken on Mac, the issue with Fira sans was revealed in habrahabr.ru redesign (worked fine on Windows but was totally invisible on Mac/Linux). It looks like this: 
![2016-12-07_21-01-23](https://cloud.githubusercontent.com/assets/184066/20980123/5a7fc3ca-bcc0-11e6-86f4-3d51836a135b.png)
Disabling `font-family` in `body` reveals the text. Please replace the font with the working version.

**Comment by transcranial** [comment]
It's getting it from fonts.googleapis.com, so I imagine it's a local issue.

**Comment by rkfg** [comment]
Google isn't impeccable, and it's not local. Here's the issue: https://github.com/google/fonts/issues/10

**Comment by transcranial** [comment]
Ha, thanks for shattering my worldview. Just switched to Open Sans - let me know if there's still any problems.

**Comment by rkfg** [comment]
Thanks, now it looks just fine!
