### ISSUE TITLE
Looking for library to train in the browser

### ISSUE THREAD

**Issue by runvnc** [transcranial/keras-js#43]
Hello, if I understand correctly, this can only work for pre-trained networks?  If so, do you know of another deep NN library that works in the browser and uses the GPU (WebGL) and allows training in the browser Thanks.

**Comment by transcranial** [comment]
There aren't any other libraries that lets you use the GPU through WebGL for training (that I know of). Convnetjs is your best bet for training in JS. I think there was some mention of incorporating WebGL or SIMD but I don't believe it got anywhere.

Using WebGL for GPGPU is quite difficult and limited. I think we'll have to wait for [further developments](https://webkit.org/blog/7380/next-generation-3d-graphics-on-the-web/) before this becomes the realm of practical reality.

**Comment by unsalted** [comment]
Recurrent.js (also karpathy) works for RNN.
As far as i'm not GPU either.

http://cs.stanford.edu/people/karpathy/recurrentjs/
