### ISSUE TITLE
Error when importing keras.js in index.html

### ISSUE THREAD

**Issue by amidos2006** [transcranial/keras-js#45]
Hello everyone,
I am not an experienced developer with JS but I get weird error.

This is the error:
![Error Image](https://dl.dropboxusercontent.com/u/9791999/Screen%20Shot%202017-02-18%20at%204.26.23%20PM.png)

This is my whole code (its just a simple testing code):
```
<!DOCTYPE html>
<html>
  <head>
    <title>Testing Deep Tingle</title>
    <meta charset="utf-8" />
  </head>
  <body>

  </body>
  <script src="dist/keras.js"></script>
  <script>
    const model = new KerasJS.Model({
      filepaths: {
        model: 'Gabb_Data/model.json',
        weights: 'Gabb_Data/model_weights.buf',
        metadata: 'Gabb_Data/model_metadata.json'
      },
      gpu: true
    });
    // model.ready().then(() => {}).catch(err => {});
  </script>
</html>
```

**Comment by amidos2006** [comment]
It worked when I relaunched my python server seems something was wrong with the old one

**Comment by dribnet** [comment]
I can't see your error, but had strange errors myself when I removed this line from the html:
```html
<meta charset="utf-8">
```
