### ISSUE TITLE
Heads up, $5k grant for OSS AI projects :)

### ISSUE THREAD

**Issue by tuckerconnelly** [transcranial/keras-js#59]
Reallllly stoked for keras-js, this might help the project:

https://nat.org/aigrant-get-5-000-for-your-open-source-ai-project-1118dd7db083

**Comment by transcranial** [comment]
@tuckerconnelly definitely. thanks for the suggestion!

**Comment by dribnet** [comment]
(fwiw: I actually went through the steps of nominating keras-js for this grant, but it did not get accepted)
