### ISSUE TITLE
Error loading demo model ("RangeError: Invalid typed array length")

### ISSUE THREAD

**Issue by mobeets** [transcranial/keras-js#61]
Hi, I am trying to load the mnist_vae model weights demo with the following html:

````html
<html>
<head>
  <meta charset="utf-8">
  <script language="javascript" type="text/javascript" src="scripts/lib/keras.js"></script>
</head>
<body>
  <script language="javascript" type="text/javascript">
	  const model = new KerasJS.Model({
	  filepaths: {
	    model: 'static/model/mnist_vae.json',
	    weights: 'static/model/mnist_vae_weights.buf',
	    metadata: 'static/model/mnist_vae_metadata.json'
	  },
	  gpu: false
	});
  </script>
</body>
</html>
````

This is the error I get in Chrome:
````
RangeError: Invalid typed array length
    at new Float32Array (native)
    at http://0.0.0.0:8000/scripts/lib/keras.js:4:18505
    at Array.map (native)
    at http://0.0.0.0:8000/scripts/lib/keras.js:4:18250
    at Array.forEach (native)
    at t.value (http://0.0.0.0:8000/scripts/lib/keras.js:4:16687)
    at http://0.0.0.0:8000/scripts/lib/keras.js:4:15092
From previous event:
    at t.value (http://0.0.0.0:8000/scripts/lib/keras.js:4:15067)
    at new t (http://0.0.0.0:8000/scripts/lib/keras.js:4:14730)
    at http://0.0.0.0:8000/keras.html:8:18
````

I get a similar error in Firefox that begins with:

````
Error: WebGL: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.
RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer
Stack trace:
[...]
````

Any ideas what might be going wrong?

**Comment by dribnet** [comment]
Have you seen issue #60?

**Comment by dribnet** [comment]
Are you using weights from a model you trained yourself, or sample weights included with the repo? If your own model, was it run with Keras 1.1.0? I believe that is the only version of Keras this repo currently supports.

**Comment by mobeets** [comment]
Just the weights from the repo.

**Comment by dribnet** [comment]
Aha, yes - I believe this should work. Unsure what the issue might be then.

**Comment by mobeets** [comment]
Is there a minimal working example somewhere that you know of? I'm not familiar with Vue so it's hard to know where I'm going wrong.

**Comment by mobeets** [comment]
Strangely enough, I have no problems at all if I use different weights (like [these](https://github.com/stekaiser/keras-js-lstm-demo)). No idea what the differences between these might be.

**Comment by transcranial** [comment]
@mobeets Looks like you're just using the empty pointer files. [Git LFS](https://git-lfs.github.com/) is required to pull the actual files. This is to avoid committing the large files directly into the git repo. 

Compare this git repo's [file](https://github.com/transcranial/keras-js/blob/master/demos/data/mnist_vae/mnist_vae_weights.buf) to [the same file](https://github.com/transcranial/keras-js-demos-data/blob/master/mnist_vae/mnist_vae_weights.buf) in a second repo transcranial/keras-js-demos-data. The second repo is where the weights files are committed directly to git which enables directly serving the weights files for the demo site.

**Comment by mobeets** [comment]
Ahhhhhh that makes so much sense. Thanks a lot!
