### ISSUE TITLE
Can not initiate model in nodejs with demo models

### ISSUE THREAD

**Issue by spec2e** [transcranial/keras-js#71]
Hi

I am trying to predict on the IMDB bidrectional LSTM demo in NodeJS, so I have this code:  
```js
const KerasJS = require('keras-js');
const model = new KerasJS.Model({
    filepaths: {
        model: 'imdb_bidirectional_lstm.json',
        weights: 'imdb_bidirectional_lstm_weights.buf',
        metadata: 'imdb_bidirectional_lstm_metadata.json'
    },
    filesystem: true
});
```

When I run this, it throws this error:  

RangeError: Invalid typed array length
    at Float32Array (native)
    at D:\development\webserving\node_modules\core-js\modules\_typed-array.js:416:15
    at new Float32Array (D:\development\webserving\node_modules\core-js\modules\es6.typed.float32-array.js:3:12)
    at D:\development\webserving\node_modules\keras-js\lib\Model.js:465:30
    at Array.map (native)
    at D:\development\webserving\node_modules\keras-js\lib\Model.js:433:37
    at Array.forEach (native)
    at Model._createLayers (D:\development\webserving\node_modules\keras-js\lib\Model.js:352:19)
    at D:\development\webserving\node_modules\keras-js\lib\Model.js:195:15
    at tryCatcher (D:\development\webserving\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\development\webserving\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\development\webserving\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\development\webserving\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\development\webserving\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\development\webserving\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (D:\development\webserving\node_modules\bluebird\js\release\promise_array.js:126:19)

Any idea what I am doing wrong here?

Thanks :-)

**Comment by spec2e** [comment]
The model files are in the same folder as the code.

**Comment by spec2e** [comment]
OK - just found out that is was something with the weights. Seemed to help to update to the latest *.buf file.

Anyway, the code in nodejs is here, in case anyone is interested...

```
const KerasJS = require('keras-js');
const fs = require('fs');

const MODEL_FILEPATHS_DEV = {
    filepaths: {
        model: '../../public/imdb_bidirectional_lstm.json',
        weights: '../../public/imdb_bidirectional_lstm_weights.buf',
        metadata: '../../public/imdb_bidirectional_lstm_metadata.json'
    },
    filesystem: true
};

const MODEL_CONFIG = MODEL_FILEPATHS_DEV;

const ADDITIONAL_DATA_FILEPATHS_DEV = {
    wordIndex: '../../public/imdb_dataset_word_index_top20000.json',
    wordDict: '../../public/imdb_dataset_word_dict_top20000.json',
    testSamples: '../../public/imdb_dataset_test.json'
};

const ADDITIONAL_DATA_FILEPATHS = ADDITIONAL_DATA_FILEPATHS_DEV;
const MAXLEN = 200;
const INDEX_FROM = 3;

class ImdbBidirectionalLstm {

    constructor() {

        this.model = new KerasJS.Model(MODEL_CONFIG);
        this.modelRunning = false;
        this.input = new Float32Array(MAXLEN);
        this.output = new Float32Array(1);
        this.inputText = '';
        this.inputTextParsed = [];
        this.wordIndex = {};
        this.wordDict = {};
        this.testSamples = [];

    }

    ready() {
        let self = this;
        return new Promise((resolve, reject) => {
            self.model.ready().then(() => {
                this.loadAdditionalData().then(() => {
                    resolve();
                });
            });
        });

    }

    loadAdditionalData() {
        return new Promise((resolve, reject) => {
            console.log('loading additional data...');

            this.wordIndex = JSON.parse(fs.readFileSync(ADDITIONAL_DATA_FILEPATHS['wordIndex']));
            this.wordDict = JSON.parse(fs.readFileSync(ADDITIONAL_DATA_FILEPATHS['wordDict']));
            this.testSamples = JSON.parse(fs.readFileSync(ADDITIONAL_DATA_FILEPATHS['testSamples']));

            resolve();
        });
    }

    randomSample() {
        // Just picking an example...
        const randSampleIdx = 10;
        const values = this.testSamples[randSampleIdx].values;

        const words = values.map(idx => {
            if (idx === 0 || idx === 1) {
                return '';
            } else if (idx === 2) {
                return '<OOV>';
            } else {
                return this.wordDict[idx - INDEX_FROM];
            }
        });

        this.inputText = words.join(' ').trim();
        console.log('sample was: ' + this.inputText);

        this.inputTextParsed = words.filter(w => !!w);
        this.input = new Float32Array(values);

        return new Promise((resolve, reject) => {
            this.model.predict({input: this.input}).then(outputData => {
                resolve(outputData.output);
            });
        });
    }
}

const imdb = new ImdbBidirectionalLstm();
imdb.ready().then(() => {
    imdb.randomSample().then((output) => {
        console.log("result was: " + JSON.stringify(output));
    });

});
```

**Comment by transcranial** [comment]
@spec2e thanks! Yeah, the new weights reflect the updated Keras v2 format.
