### ISSUE TITLE
Doesn't work when MAX_TEXTURE_SIZE is not large enough

### ISSUE THREAD

**Issue by upsuper** [transcranial/keras-js#8]
It seems the script is assuming `weblasTensor` is available after calling `createWeblasTensor`. However, when `MAX_TEXTURE_SIZE` is not enough, `createWeblasTensor` may create `weblasTensorsSplit` instead (or raise an error if it is really not enough).

If it is hard to use `weblasTensorsSplit` for this, I think it would be better to show some warning and gracefully fallback to CPU.

**Comment by transcranial** [comment]
Added some [notes](https://github.com/transcranial/keras-js#notes) in the readme.
