### ISSUE TITLE
[Model] path to protobuf-serialized model definition file is missing

### ISSUE THREAD

**Issue by dparnellmitek** [transcranial/keras-js#86]
Update from master 11/10/2017 

Code builds but fails in browser, see error below. What changed?

Error: [Model] path to protobuf-serialized model definition file is missing.
new Model
./src/Model.js:34
  31 | } = config
  32 | 
  33 | if (!filepath) {
> 34 |   throw new Error('[Model] path to protobuf-serialized model definition file is missing.')
  35 | }
  36 | this.filepath = filepath
  37 |

**Comment by dparnellmitek** [comment]
Ok...I think I figured out the new process. After pull latest, npm i, run npm protojs, build keras

Then
1. Re-train/Save full model...not just the weights
2. Use new encoder on saved model -> .bin file created
3. load .bin file using file path...no more loading 3 separate files

**Comment by ghassanmas** [comment]
Is there any example for loading a keras model using only model.bin file ?
